-- ==============================================================
-- Project: Indian E-Commerce SQL Data Analysis
-- File: queries.sql
-- Description: 50+ Professional SQL queries for Data Analysis.
--              Covers Basic to Advanced PostgreSQL concepts.
-- ==============================================================

-- ==========================================
-- SECTION 1: BASIC QUERIES (SELECT, WHERE, ORDER BY, DISTINCT)
-- ==========================================

-- 1. Retrieve all active customers from Maharashtra
SELECT customer_id, first_name, last_name, city, state 
FROM Customers 
WHERE state = 'Maharashtra' 
ORDER BY city;

-- 2. Find all products that cost more than ₹5000 and are in stock
SELECT product_id, product_name, price, stock_quantity 
FROM Products 
WHERE price > 5000 AND stock_quantity > 0;

-- 3. Get a unique list of all delivery cities where orders were shipped
SELECT DISTINCT delivery_city 
FROM Orders 
WHERE order_status IN ('Shipped', 'Delivered');

-- 4. Find all customers who registered in the year 2023
SELECT customer_id, first_name, email, registration_date 
FROM Customers 
WHERE EXTRACT(YEAR FROM registration_date) = 2023;

-- 5. List the top 10 most expensive products
SELECT product_name, price 
FROM Products 
ORDER BY price DESC 
LIMIT 10;

-- 6. Find all orders placed in the last 30 days (simulated as from current_date)
SELECT order_id, order_date, total_amount, order_status
FROM Orders
WHERE order_date >= CURRENT_DATE - INTERVAL '30 days';

-- 7. Get the details of all pending payments
SELECT payment_id, order_id, amount, payment_mode
FROM Payments
WHERE payment_status = 'Pending';

-- 8. List employees who don't have a manager (Top Level Executives)
SELECT employee_id, first_name, last_name, department
FROM Employees
WHERE manager_id IS NULL;

-- 9. Find all suppliers located in Delhi or Karnataka
SELECT supplier_name, city, state
FROM Suppliers
WHERE state IN ('Delhi', 'Karnataka');

-- 10. Search for products that have the word 'Smart' in their name
SELECT product_id, product_name, price
FROM Products
WHERE product_name ILIKE '%Smart%';


-- ==========================================
-- SECTION 2: AGGREGATION & GROUPING (GROUP BY, HAVING)
-- ==========================================

-- 11. Count the number of customers in each state
SELECT state, COUNT(customer_id) AS total_customers
FROM Customers
GROUP BY state
ORDER BY total_customers DESC;

-- 12. Find the total revenue generated by the platform (Success payments only)
SELECT SUM(amount) AS total_revenue
FROM Payments
WHERE payment_status = 'Success';

-- 13. Calculate the average order value (AOV)
SELECT ROUND(AVG(total_amount), 2) AS average_order_value
FROM Orders
WHERE order_status != 'Cancelled';

-- 14. Find categories with more than 50 products
SELECT category_id, COUNT(product_id) AS product_count
FROM Products
GROUP BY category_id
HAVING COUNT(product_id) > 50;

-- 15. Get the maximum and minimum salary in each department
SELECT department, MAX(salary) AS highest_salary, MIN(salary) AS lowest_salary
FROM Employees
GROUP BY department;

-- 16. Monthly revenue trend for the year 2023
SELECT EXTRACT(MONTH FROM order_date) AS month, SUM(total_amount) AS monthly_revenue
FROM Orders
WHERE EXTRACT(YEAR FROM order_date) = 2023 AND order_status IN ('Delivered', 'Shipped')
GROUP BY EXTRACT(MONTH FROM order_date)
ORDER BY month;

-- 17. Count of orders by order status
SELECT order_status, COUNT(order_id) AS number_of_orders
FROM Orders
GROUP BY order_status;

-- 18. Find the total quantity sold for each product
SELECT product_id, SUM(quantity) AS total_quantity_sold
FROM Order_Items
GROUP BY product_id
ORDER BY total_quantity_sold DESC;

-- 19. Identify the top 5 most popular payment modes
SELECT payment_mode, COUNT(payment_id) AS transaction_count
FROM Payments
GROUP BY payment_mode
ORDER BY transaction_count DESC
LIMIT 5;

-- 20. Find states generating more than ₹1,000,000 in revenue
SELECT delivery_state, SUM(total_amount) AS state_revenue
FROM Orders
WHERE order_status = 'Delivered'
GROUP BY delivery_state
HAVING SUM(total_amount) > 1000000
ORDER BY state_revenue DESC;


-- ==========================================
-- SECTION 3: JOINS (INNER, LEFT, RIGHT, FULL, SELF, CROSS)
-- ==========================================

-- 21. (INNER JOIN) List order details along with customer names
SELECT o.order_id, c.first_name, c.last_name, o.order_date, o.total_amount
FROM Orders o
INNER JOIN Customers c ON o.customer_id = c.customer_id;

-- 22. (LEFT JOIN) Find all customers and their orders, including customers with zero orders
SELECT c.customer_id, c.first_name, COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name;

-- 23. (RIGHT JOIN) List all products and their category names, ensuring all categories are shown
SELECT p.product_name, c.category_name
FROM Products p
RIGHT JOIN Categories c ON p.category_id = c.category_id;

-- 24. (FULL JOIN) Find mismatch between orders and payments (e.g. order exists but no payment record)
SELECT o.order_id, p.payment_id, o.total_amount, p.amount
FROM Orders o
FULL JOIN Payments p ON o.order_id = p.order_id
WHERE o.order_id IS NULL OR p.payment_id IS NULL;

-- 25. (SELF JOIN) List employees and the names of their managers
SELECT e.first_name AS employee_name, m.first_name AS manager_name
FROM Employees e
LEFT JOIN Employees m ON e.manager_id = m.employee_id;

-- 26. (CROSS JOIN) Create a combination of all categories and order statuses for a matrix report
SELECT c.category_name, os.status
FROM Categories c
CROSS JOIN (SELECT DISTINCT order_status AS status FROM Orders) os;

-- 27. Multiple Joins: Get complete order receipt (Order ID, Customer Name, Product Name, Qty, Price)
SELECT o.order_id, c.first_name, p.product_name, oi.quantity, oi.unit_price, oi.total_price
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE o.order_id = 1001; -- Replace 1001 with specific order_id

-- 28. Find the total revenue generated by each category
SELECT c.category_name, SUM(oi.total_price) AS revenue
FROM Categories c
JOIN Products p ON c.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
JOIN Orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY c.category_name
ORDER BY revenue DESC;

-- 29. Find the supplier for the most sold product
SELECT s.supplier_name, p.product_name, SUM(oi.quantity) AS total_sold
FROM Suppliers s
JOIN Products p ON s.supplier_id = p.supplier_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY s.supplier_name, p.product_name
ORDER BY total_sold DESC
LIMIT 1;

-- 30. Find customers who have purchased products from 'Electronics' category
SELECT DISTINCT c.first_name, c.last_name, c.email
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
JOIN Categories cat ON p.category_id = cat.category_id
WHERE cat.category_name = 'Electronics';


-- ==========================================
-- SECTION 4: SUBQUERIES & CTEs
-- ==========================================

-- 31. (Subquery) Find products with a price higher than the average product price
SELECT product_name, price 
FROM Products 
WHERE price > (SELECT AVG(price) FROM Products);

-- 32. (Correlated Subquery) Find customers whose latest order was placed in the last 10 days
SELECT customer_id, first_name 
FROM Customers c
WHERE EXISTS (
    SELECT 1 
    FROM Orders o 
    WHERE o.customer_id = c.customer_id 
    AND order_date >= CURRENT_DATE - INTERVAL '10 days'
);

-- 33. (Subquery in FROM) Calculate the average number of orders per customer
SELECT AVG(order_count) AS avg_orders_per_customer
FROM (
    SELECT customer_id, COUNT(order_id) AS order_count
    FROM Orders
    GROUP BY customer_id
) sub;

-- 34. (CTE) Find the Top 5 Customers by Lifetime Value (LTV)
WITH CustomerRevenue AS (
    SELECT customer_id, SUM(total_amount) AS lifetime_value
    FROM Orders
    WHERE order_status = 'Delivered'
    GROUP BY customer_id
)
SELECT c.first_name, c.last_name, cr.lifetime_value
FROM Customers c
JOIN CustomerRevenue cr ON c.customer_id = cr.customer_id
ORDER BY cr.lifetime_value DESC
LIMIT 5;

-- 35. (CTE) Monthly Active Customers (MAC)
WITH MonthlyCustomers AS (
    SELECT EXTRACT(MONTH FROM order_date) AS month, 
           EXTRACT(YEAR FROM order_date) AS year,
           COUNT(DISTINCT customer_id) AS active_customers
    FROM Orders
    GROUP BY EXTRACT(YEAR FROM order_date), EXTRACT(MONTH FROM order_date)
)
SELECT year, month, active_customers 
FROM MonthlyCustomers 
ORDER BY year, month;

-- 36. (Recursive CTE) Generate an Employee Hierarchy (Org Chart)
WITH RECURSIVE OrgChart AS (
    -- Anchor member: Start with top-level managers
    SELECT employee_id, first_name, manager_id, 1 AS level
    FROM Employees
    WHERE manager_id IS NULL
    
    UNION ALL
    
    -- Recursive member: Find employees managed by the previous level
    SELECT e.employee_id, e.first_name, e.manager_id, oc.level + 1
    FROM Employees e
    INNER JOIN OrgChart oc ON e.manager_id = oc.employee_id
)
SELECT * FROM OrgChart ORDER BY level, manager_id;

-- 37. Find products that have never been ordered
SELECT product_id, product_name 
FROM Products 
WHERE product_id NOT IN (SELECT DISTINCT product_id FROM Order_Items);

-- 38. Find the most recent order for each customer using a Correlated Subquery
SELECT o1.customer_id, o1.order_id, o1.order_date
FROM Orders o1
WHERE o1.order_date = (
    SELECT MAX(order_date) 
    FROM Orders o2 
    WHERE o2.customer_id = o1.customer_id
);

-- 39. (CTE) Identify customers with abandoned carts (Simulated: Pending orders without successful payment)
WITH AbandonedOrders AS (
    SELECT o.order_id, o.customer_id
    FROM Orders o
    LEFT JOIN Payments p ON o.order_id = p.order_id
    WHERE o.order_status = 'Pending' AND (p.payment_status != 'Success' OR p.payment_id IS NULL)
)
SELECT c.first_name, c.email, a.order_id 
FROM Customers c 
JOIN AbandonedOrders a ON c.customer_id = a.customer_id;

-- 40. Determine the percentage contribution of each category to total revenue
WITH CategoryRevenue AS (
    SELECT c.category_name, SUM(oi.total_price) AS revenue
    FROM Categories c
    JOIN Products p ON c.category_id = p.category_id
    JOIN Order_Items oi ON p.product_id = oi.product_id
    GROUP BY c.category_name
), TotalRevenue AS (
    SELECT SUM(revenue) AS total FROM CategoryRevenue
)
SELECT cr.category_name, cr.revenue, 
       ROUND((cr.revenue / tr.total) * 100, 2) AS percentage_contribution
FROM CategoryRevenue cr, TotalRevenue tr
ORDER BY percentage_contribution DESC;


-- ==========================================
-- SECTION 5: WINDOW FUNCTIONS
-- ==========================================

-- 41. (ROW_NUMBER) Find the first order placed by each customer
WITH RankedOrders AS (
    SELECT customer_id, order_id, order_date,
           ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY order_date ASC) as rn
    FROM Orders
)
SELECT customer_id, order_id, order_date FROM RankedOrders WHERE rn = 1;

-- 42. (RANK) Rank products within each category based on price
SELECT category_id, product_name, price,
       RANK() OVER(PARTITION BY category_id ORDER BY price DESC) as price_rank
FROM Products;

-- 43. (DENSE_RANK) Rank employees by salary within their departments
SELECT department, first_name, salary,
       DENSE_RANK() OVER(PARTITION BY department ORDER BY salary DESC) as salary_rank
FROM Employees;

-- 44. (LAG) Calculate month-over-month (MoM) revenue growth
WITH MonthlyRev AS (
    SELECT DATE_TRUNC('month', order_date) AS order_month, SUM(total_amount) AS revenue
    FROM Orders WHERE order_status = 'Delivered'
    GROUP BY DATE_TRUNC('month', order_date)
)
SELECT order_month, revenue,
       LAG(revenue) OVER(ORDER BY order_month) AS prev_month_rev,
       ROUND(((revenue - LAG(revenue) OVER(ORDER BY order_month)) / LAG(revenue) OVER(ORDER BY order_month)) * 100, 2) AS mom_growth_pct
FROM MonthlyRev;

-- 45. (LEAD) Find the time gap between a customer's current order and their next order
WITH CustomerOrders AS (
    SELECT customer_id, order_id, order_date,
           LEAD(order_date) OVER(PARTITION BY customer_id ORDER BY order_date) AS next_order_date
    FROM Orders
)
SELECT customer_id, order_id, order_date, next_order_date,
       EXTRACT(DAY FROM (next_order_date - order_date)) AS days_until_next_order
FROM CustomerOrders;

-- 46. (Running Total) Calculate the cumulative revenue over time
SELECT order_date, total_amount,
       SUM(total_amount) OVER(ORDER BY order_date) AS cumulative_revenue
FROM Orders
WHERE order_status = 'Delivered';

-- 47. Find the top 2 highest selling products in each category (using ROW_NUMBER)
WITH CategorySales AS (
    SELECT p.category_id, p.product_name, SUM(oi.quantity) as qty_sold,
           ROW_NUMBER() OVER(PARTITION BY p.category_id ORDER BY SUM(oi.quantity) DESC) as rn
    FROM Products p
    JOIN Order_Items oi ON p.product_id = oi.product_id
    GROUP BY p.category_id, p.product_name
)
SELECT category_id, product_name, qty_sold FROM CategorySales WHERE rn <= 2;

-- 48. NTILE - Segment customers into 4 quartiles based on their total spending
WITH CustomerSpend AS (
    SELECT customer_id, SUM(total_amount) AS total_spent
    FROM Orders GROUP BY customer_id
)
SELECT customer_id, total_spent,
       NTILE(4) OVER(ORDER BY total_spent DESC) AS spending_quartile
FROM CustomerSpend;

-- 49. (Moving Average) Calculate a 7-day moving average of daily revenue
WITH DailyRev AS (
    SELECT CAST(order_date AS DATE) AS d_date, SUM(total_amount) AS daily_revenue
    FROM Orders GROUP BY CAST(order_date AS DATE)
)
SELECT d_date, daily_revenue,
       AVG(daily_revenue) OVER(ORDER BY d_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS moving_avg_7d
FROM DailyRev;

-- 50. Percent_Rank of products based on price
SELECT product_name, price,
       ROUND(CAST(PERCENT_RANK() OVER(ORDER BY price) AS NUMERIC), 2) AS price_percentile
FROM Products;


-- ==========================================
-- SECTION 6: ADVANCED (CASE WHEN, VIEWS, STRINGS)
-- ==========================================

-- 51. (CASE WHEN) Customer Segmentation based on Lifetime Value (LTV)
SELECT c.customer_id, c.first_name, SUM(o.total_amount) AS ltv,
       CASE 
           WHEN SUM(o.total_amount) > 50000 THEN 'Platinum'
           WHEN SUM(o.total_amount) BETWEEN 10000 AND 50000 THEN 'Gold'
           WHEN SUM(o.total_amount) BETWEEN 1000 AND 9999 THEN 'Silver'
           ELSE 'Bronze'
       END AS customer_tier
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name;

-- 52. View Creation: Create a View for Daily Sales Report
CREATE OR REPLACE VIEW Daily_Sales_Report AS
SELECT CAST(order_date AS DATE) AS sale_date, 
       COUNT(order_id) AS total_orders, 
       SUM(total_amount) AS total_revenue
FROM Orders
WHERE order_status = 'Delivered'
GROUP BY CAST(order_date AS DATE);

-- 53. Query the view
SELECT * FROM Daily_Sales_Report ORDER BY sale_date DESC LIMIT 10;

-- 54. String Aggregation: List all products bought by a specific customer (e.g. customer_id = 5)
SELECT o.customer_id, STRING_AGG(p.product_name, ', ') AS products_bought
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE o.customer_id = 5
GROUP BY o.customer_id;

-- 55. Data Cleaning Simulation: Find customers with invalid email formats using Regex
SELECT customer_id, email
FROM Customers
WHERE email !~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$';
